databases:
  - name: soundofthesun
    databaseName: soundofthesun
    user: soundofthesun
    plan: free

services:
  - type: web
    name: soundofthesun
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soundofthesun
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false